spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-bdtcc.alwaysdata.net:3306/bdtcc_achadoseperdidos
    username: bdtcc 
    password: _VRwe3r2S.yBEki 
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8080
