spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: b5bbbuxwfp7oi4fifmra-mysql.services.clever-cloud.com:3306/b5bbbuxwfp7oi4fifmra?useTimezone=true&serverTimezone=UTC
    username: udipumpybj3yp5x0 
    password: UTj09FBeV07RICRp1Eqg 
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8080
